Trip.PasvAPI/Controllers/CodeController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;
using Trip.PasvAPI.Models;
using Trip.PasvAPI.Models.Repository;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Trip.PasvAPI.Controllers
{
    [Authorize(AuthenticationSchemes = "Broker.Staff", Policy = "Staff.Only")]
    public class CodeController : Controller
    {
        const int PAGE_SIZE = 50;

        //private IMapper _mapper;

        //public CodeController(IMapper mapper)
        //{
        //    this._mapper = mapper;
        //}
          
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        ///   產出結果給 bootstrap-table
        /// </summary>
        /// <param name="filter">Json String (Nullable)</param>
        /// <param name="sort">Filed-Name</param>
        /// <param name="order">Asc/Desc</param>
        /// <param name="offset">Skip</param>
        /// <param name="limit">Size</param>
        /// <returns></returns>
        public IActionResult FetchData(string filter, string sort, string order, int offset, int limit)
        {
            Dictionary<string, object> jsonData = new Dictionary<string, object>();

            try
            {
                var codeRepos = HttpContext.RequestServices.GetService<CodeRepository>();

                int totalCount = codeRepos.GetCount(filter);
                var sorting = string.IsNullOrEmpty(sort) ? string.Empty : $"{sort} {order}";
                var codes = codeRepos.GetCodes(filter, sorting, limit, offset, CultureInfo.CurrentCulture.ToString());

                jsonData.Add("total", totalCount);
                jsonData.Add("totalNotFiltered", totalCount);
                jsonData.Add("rows", codes);
            }
            catch (Exception ex)
            {
                // Website.Instance.logger.Fatal($"Exception:Message={ex.Message},StackTrace={ex.StackTrace}");
                jsonData.Add("total", 0);
                jsonData.Add("totalNotFiltered", 0);
                jsonData.Add("rows", new string[] { });
            }

            return Json(jsonData);
        }

        public IActionResult Add()
        {
            var code = new CodeModel() { code_name = new Dictionary<string, string>() };

            return View("Edit", code);
        }

        public IActionResult InsertItem([FromBody] CodeModel req)
        {
            var jsonData = new Dictionary<string, object>();

            try
            {
                var codeRepos = HttpContext.RequestServices.GetService<CodeRepository>();
                req.create_user = "SYSTEM";  // User.FindFirst("Account").Value;
                codeRepos.InsertItem(req);

                jsonData.Add("status", true);
            }
            catch (Exception ex)
            {
                // Website.Instance.logger.FatalFormat("Message={0},StackTrace={1}", ex.Message, ex.StackTrace);
                jsonData.Clear();
                jsonData.Add("status", false);
                jsonData.Add("msg", ex.Message);
            }

            return Json(jsonData);
        }

        public IActionResult Edit(Int64 id)
        {
            var codeRepos = HttpContext.RequestServices.GetService<CodeRepository>();
            var code = codeRepos.GetCode(id);

            ViewBag.CodeNames = code.code_name;

            return View(code);
        }

        // 自動完成(Auto-Complete) 查詢專用
        public IActionResult QueryCodeTypes(string id)
        {
            try
            {
                var codeRepos = HttpContext.RequestServices.GetService<CodeRepository>();
                List<string> geoCities = codeRepos.GetCodeTypesForAC(id);

                return Json(geoCities);
            }
            catch (Exception ex)
            {
                // Website.Instance.logger.FatalFormat("Message={0},StackTrace={1}", ex.Message, ex.StackTrace);
                return Json(string.Empty);
            }
        }

        public IActionResult UpdateItem([FromBody] CodeModel req)
        {
            var jsonData = new Dictionary<string, object>();

            try
            {
                var codeRepos = HttpContext.RequestServices.GetService<CodeRepository>();
                req.modify_user = "SYSTEM";  // User.FindFirst("Account").Value;
                codeRepos.UpdateItem(req);

                jsonData.Add("status", true);
            }
            catch (Exception ex)
            {
                // Website.Instance.logger.FatalFormat("Message={0},StackTrace={1}", ex.Message, ex.StackTrace);
            }

            return Json(jsonData);
        }
    }
}

Trip.PasvAPI/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Trip.PasvAPI.AppCode;
using Trip.PasvAPI.Models.Repository;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Trip.PasvAPI.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
         
        public async Task<IActionResult> SignInAsync(string account, string passwd)
        {
             var jsonData = new Dictionary<string, object>();

            try
            {
                var clientIP = Request.HttpContext.Connection.RemoteIpAddress.ToString().Replace("::1", "127.0.0.1");
                var staffRepos = HttpContext.RequestServices.GetService<StaffRepository>();
                 
                var staff = staffRepos.GetStaff(account: account, passwd: AesCryptHelper.aesEncryptBase64(passwd, Website.Instance.AesCryptoKey));
                if (staff == null) throw new NullReferenceException("無效的帳號或密碼，請重新輸入!");
                 
                var claims = new List<Claim>
                {
                    new Claim("Account", staff.staff_account),
                    new Claim(ClaimTypes.Name, staff.staff_name),
                    new Claim(ClaimTypes.Email, staff.staff_account), 
                    new Claim("IdentityType", "USER"),
                    new Claim("IP", clientIP), //IpAddress 存於Claims 
                    new Claim("Ver", Website.Instance.PrincipleVersion), // 帶入當前ClaimPriciple版號
                };

                var userIdentity = new ClaimsIdentity(claims, "login");

                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

                await HttpContext.SignInAsync(
                   "Broker.Staff",
                    principal,
                    new AuthenticationProperties()
                    {
                        ExpiresUtc = DateTime.UtcNow.AddDays(10), // 預設 Cookie 有效時間
                        IsPersistent = true, // req.RememberMe,
                        AllowRefresh = true
                    });

                jsonData.Add("status", true);
            }
            catch (Exception ex)
            {
                // Website.Instance.logger.FatalFormat("Message={0},StackTrace={1}", ex.Message, ex.StackTrace);
                jsonData.Clear();
                jsonData.Add("status", false);
                jsonData.Add("msg", ex.Message);
            }

            return Json(jsonData);
        }
         
        public async Task<IActionResult> SignOutAsync()
        { 
            // 清除已登入 User
            await HttpContext.SignOutAsync("Broker.Staff");

            return Redirect("~/");
        }

    }
}

Trip.PasvAPI/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization; 
using Microsoft.Extensions.DependencyInjection;
using Trip.PasvAPI.Models.Repository;
using System.Globalization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Trip.PasvAPI.Controllers
{
    [Authorize(AuthenticationSchemes = "Broker.Staff", Policy = "Staff.Only")]
    public class OrderController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FetchData(string filter, string sort, string order, int offset, int limit)
        {
            Dictionary<string, object> jsonData = new Dictionary<string, object>();

            try
            {
                var orderRepos = HttpContext.RequestServices.GetService<OrderMasterRepository>();

                int totalCount = orderRepos.GetCount(filter);
                var sorting = string.IsNullOrEmpty(sort) ? string.Empty : $"{sort} {order}";
                var codes = orderRepos.GetOrders(filter, sorting, limit, offset);

                jsonData.Add("total", totalCount);
                jsonData.Add("totalNotFiltered", totalCount);
                jsonData.Add("rows", codes);
            }
            catch (Exception ex)
            {
                // Website.Instance.logger.Fatal($"Exception:Message={ex.Message},StackTrace={ex.StackTrace}");
                jsonData.Add("total", 0);
                jsonData.Add("totalNotFiltered", 0);
                jsonData.Add("rows", new string[] { });
            }

            return Json(jsonData);
        }

    }
}

Trip.PasvAPI/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;
using Trip.PasvAPI.AppCode;
using Trip.PasvAPI.Models.Model;
using Trip.PasvAPI.Models.Repository;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Trip.PasvAPI.Controllers
{
    [Authorize(AuthenticationSchemes = "Broker.Staff", Policy = "Staff.Only")]
    public class StaffController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        ///   產出結果給 bootstrap-table
        /// </summary> 
        public IActionResult FetchData(string filter, string sort, string order, int offset, int limit)
        {
            Dictionary<string, object> jsonData = new Dictionary<string, object>();

            try
            {
                var staffRepos = HttpContext.RequestServices.GetService<StaffRepository>();

                int totalCount = staffRepos.GetCount(filter);
                var sorting = string.IsNullOrEmpty(sort) ? string.Empty : $"{sort} {order}";
                var staffs = staffRepos.GetStaffs(filter, sorting, limit, offset, CultureInfo.CurrentCulture.ToString());

                jsonData.Add("total", totalCount);
                jsonData.Add("totalNotFiltered", totalCount);
                jsonData.Add("rows", staffs);
            }
            catch (Exception ex)
            {
                Website.Instance.logger.Fatal($"Exception:Message={ex.Message},StackTrace={ex.StackTrace}");
                jsonData.Add("total", 0);
                jsonData.Add("totalNotFiltered", 0);
                jsonData.Add("rows", new string[] { });
            }

            return Json(jsonData);
        }

        public IActionResult Add()
        {
            var staff = new StaffModel();

            return View("Edit", staff);
        }

        public IActionResult Insert([FromBody] StaffModel req)
        {
            var jsonData = new Dictionary<string, object>();

            try
            {
                var staffRepos = HttpContext.RequestServices.GetService<StaffRepository>();
                req.create_user = "SYSTEM"; // User.FindFirst("Account").Value;
                staffRepos.Insert(req);

                jsonData.Add("status", true);
            }
            catch (Exception ex)
            {
                Website.Instance.logger.FatalFormat("Message={0},StackTrace={1}", ex.Message, ex.StackTrace);
                jsonData.Clear();
                jsonData.Add("status", false);
                jsonData.Add("msg", ex.Message);
            }

            return Json(jsonData);
        }

        public IActionResult Edit(Int64 id)
        {
            var locale = CultureInfo.CurrentCulture.ToString();
            var staffRepos = HttpContext.RequestServices.GetService<StaffRepository>();
            var staff = staffRepos.GetStaff(oid: id, locale: locale);

            return View(staff);
        }

        public IActionResult Update([FromBody] StaffModel req)
        {
            var jsonData = new Dictionary<string, object>();

            try
            {
                var staffRepos = HttpContext.RequestServices.GetService<StaffRepository>();
                req.modify_user = "SYSTEM"; // User.FindFirst("Account").Value;
                staffRepos.Update(req);

                jsonData.Add("status", true);
            }
            catch (Exception ex)
            {
                Website.Instance.logger.FatalFormat("Message={0},StackTrace={1}", ex.Message, ex.StackTrace);
                jsonData.Clear();
                jsonData.Add("status", false);
                jsonData.Add("msg", ex.Message);
            }

            return Json(jsonData);
        }

        public IActionResult Password(Int64 id)
        {
            var locale = CultureInfo.CurrentCulture.ToString();
            var staffRepos = HttpContext.RequestServices.GetService<StaffRepository>();
            var staff = staffRepos.GetStaff(oid: id, locale: locale);

            return View(staff);
        }

        public IActionResult SetPassword(Int64 oid, string psw)
        {
            var jsonData = new Dictionary<string, object>();

            try
            {
                var staffRepos = HttpContext.RequestServices.GetService<StaffRepository>();
                var modify_user = "SYSTEM"; // User.FindFirst("Account").Value;
                staffRepos.SetPassword(oid, AesCryptHelper.aesEncryptBase64(psw, Website.Instance.AesCryptoKey), modify_user);

                jsonData.Add("status", true);
            }
            catch (Exception ex)
            {
                Website.Instance.logger.FatalFormat("Message={0},StackTrace={1}", ex.Message, ex.StackTrace);
                jsonData.Clear();
                jsonData.Add("status", false);
                jsonData.Add("msg", ex.Message);
            }

            return Json(jsonData);
        }
    }
}

Trip.PasvAPI/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Trip.PasvAPI.AppCode

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trip.PasvAPI</title>
    <link rel="stylesheet" href="~/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-validator/dist/css/bootstrapValidator.css" />
    @RenderSection("Styles", required: false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-validator/dist/js/bootstrapValidator.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <script>
        var _root_path = '@Url.Content("~/")';
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trip.PasvAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">首頁</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">員工管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductMap" asp-action="Index">商品對應</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">訂單查詢</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Code" asp-action="Index">編碼維護</a>
                        </li>

                         <li class="nav-item d-flex justify-content-end ml-auto">
                             <div class="d-flex justify-content-between align-items-center">
                                 <span> @User.FindFirst(ClaimTypes.Name)?.Value </span>
                                 <a class="btn btn-warning btn-sm ml-1" asp-area="" asp-controller="Login" asp-action="SignOut">登出</a>
                             </div>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    @*<div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>*@
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Trip.PasvAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
  
    @RenderSection("Scripts", required: false)
</body>
</html>

Trip.PasvAPI/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trip.PasvAPI</title>
    <link rel="stylesheet" href="~/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-validator/dist/css/bootstrapValidator.css" />
    @RenderSection("Styles", required: false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-validator/dist/js/bootstrapValidator.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <script>
        var _root_path = '@Url.Content("~/")';
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trip.PasvAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> 
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Trip.PasvAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
  
    @RenderSection("Scripts", required: false)
</body>
</html>